### ISSUE TITLE
System.AccessViolationException on listener set.

### ISSUE THREAD

**Issue by MarcoRoccagliSigma** [jmmorato/openddsharp#137] opened 2022-12-15 07:59 UTC
Hi,
I'm attemping to set a datareader listener to inbuilt topic "DCPSParticipant" and while executing the setlistener method, i receive the AccessViolationException.
Here there is the snippet code that i'm trying to use:

static void Main(string[] args)
        {
            Ace.Init();

            DomainParticipantFactory dpf = ParticipantService.Instance.GetDomainParticipantFactory("-DCPSConfigFile", "rtps.ini");
            DomainParticipant participant = dpf.CreateParticipant(42);
            if (participant == null)
            {
                throw new Exception("Could not create the participant");
            }

            // Include your program here

            TestExample.TestTypeSupport testsupport= new TestExample.TestTypeSupport();
            testsupport.RegisterType(participant, testsupport.GetTypeName());

            Topic topic = participant.CreateTopic("TestTopic", testsupport.GetTypeName());

            Publisher pub= participant.CreatePublisher();

            DataWriter dw = pub.CreateDataWriter(topic);
            TestExample.TestDataWriter tdw = new(dw);
           
           
            DataReader participantdr = participant.GetBuiltinSubscriber().LookupDataReader("DCPSParticipant");
            **participantdr.SetListener(new CustomDCPSParticipantListener());**

            while (true)
            {
                tdw.Write(new() { Key = 0, Message="Test" });
                System.Threading.Thread.Sleep(1000);
            }

            participant.DeleteContainedEntities();
            dpf.DeleteParticipant(participant);
            ParticipantService.Instance.Shutdown();

            Ace.Fini();
        }

Of course CustomDCPSParticipantListener extends from DataReaderListener.
Any clue for this?

Thanks

**Comment by jmmorato** [comment] 2022-12-15 09:34
I couldn't reproduce it with the latest [0.8.22323.102-beta](https://www.nuget.org/packages/OpenDDSharp.Standard/0.8.22323.102-beta) version.

What version are you using?

**Comment by MarcoRoccagliSigma** [comment] 2022-12-15 09:45
Hi using the 0.8.22127.96 that comes with standard .NET templates

**Comment by MarcoRoccagliSigma** [comment] 2022-12-15 10:14
Just to inform that i updated at same version that you suggested and the problem persists.

**Comment by jmmorato** [comment] 2022-12-15 10:29
Same for me but in the other way around, downgraded to your version and still couldn't reproduce the issue.

Could you share your full projects files please?

**Comment by MarcoRoccagliSigma** [comment] 2022-12-15 10:39
That's a WeTransfer link because of size (around 140MB)

https://we.tl/t-kRT5P9MGXz

**Comment by jmmorato** [comment] 2022-12-15 14:42
I reproduced (only happens in windows) and fixed in #138, if all tests are successfully I will create a new beta version after merging.

PD:
> That's a WeTransfer link because of size (around 140MB)

Next time remove `bin`, `obj` and `.vs` folders before zipping ;)

**Comment by MarcoRoccagliSigma** [comment] 2022-12-15 14:52
Thanks i will try and let you know ASAP

**Comment by jmmorato** [comment] 2022-12-16 07:30
Version [0.8.22349.103-beta](https://www.nuget.org/packages/OpenDDSharp.Standard/0.8.22349.103-beta) has been published

**Closed** 2022-12-19 14:53 UTC
