### ISSUE TITLE
Fail to run the HelloWorld

### ISSUE THREAD

**Issue by cheoalfredo** [jmmorato/openddsharp#28] opened 2020-10-21 12:57 UTC
the first time i tried to run the helloworld sample, i had problems building the TestMessage Project : Cannot open include file: 'TestMessageTypeSupportImpl.h'.  i deleted the folders obj and bin, still no luck. So i opted for creating a new one, basically a copy of TestMessage (TestMsg) and this one worked like a charm. when trying to build the publisher i get this error : **The expression "[System.IO.Path]::GetFullPath('')" cannot be evaluated. The path is not of a legal form.**. creating a new solution as explained in http://www.openddsharp.com/Documentation/GetStarted but i end up getting the same error. any pointers ?

**Comment by jmmorato** [comment] 2020-10-21 15:37
Hi @cheoalfredo,

I cannot reproduce your issue, just few question to try it to figure out:

* Have you installed Windows SDK 10.0.16299.0? 
* What version of Visual Studio are you using?
* What version of OpenDDSharp are you using?
* What platform and configuration are you using (Debug|Release, x86|x64)?

**Comment by cheoalfredo** [comment] 2020-10-21 15:52
thanks for getting back so quickly.

1. i have the windows 10 sdk 10.0.16299.0 installed
2. i'm using visual studio prof. 2019 v 16.7.2
3. i'm using openddsharp v0.5.0
4. as for the platform i'm using debug x64

**Comment by jmmorato** [comment] 2020-10-21 16:06
Everything seems in place... weird.

Could you zip and share your solution so I can take a look in my computer?

**Comment by cheoalfredo** [comment] 2020-10-21 18:01
sure thing [HelloWorld.zip](https://github.com/jmmorato/openddsharp/files/5417878/HelloWorld.zip)

**Comment by jmmorato** [comment] 2020-10-22 05:54
I see some issues in your solution:
- The `HelloWorldPublisher` has a reference to the `OpenDDSharp.IdlGenerator`, that creates conflicts with the main `OpenDDSharp` package. The IdlGenerator package must only be used in the VC++ IDL projects.
- The `packages.config` file is broken in the `HelloWorldSubscriber` project
- You don't need to add a new configuration `Win32` to the solution. I fixed project configurations in the solution and cleaned up the new one.

I guess all the previous errors are added while you were trying to fix the `TestMessage` project compilation. The problem there is that you tried to downgrade from `v0.5.1` to `0.5.0` where the include C++ library folder and the additional library linker folder have changed. I fixed them manually and now `TestMessage` project is compiling correctly.

Attached the modified solution, let me know if work for you now.
[HelloWorld_Modified.zip](https://github.com/jmmorato/openddsharp/files/5420370/HelloWorld_Modified.zip)

**Comment by cheoalfredo** [comment] 2020-10-26 12:27
@jmmorato thanks a million, i coud get the example to run, awesome. are there any examples having conditions that i can use to get started ??

**Comment by jmmorato** [comment] 2020-10-28 07:20
@cheoalfredo Take a look to the unit test project:
https://github.com/jmmorato/openddsharp/blob/b81a7d41e669743962498d3ac038ff28cf285968/OpenDDSharp/OpenDDSharp.UnitTest/DataReaderTest.cs#L905

I'm going to close the issue, feel free to contact again if you need something else.

Happy coding!!

**Closed by jmmorato** 2020-10-28 07:20 UTC
