### ISSUE TITLE
Hello World Example not working in a inter-host scenario

### ISSUE THREAD

**Issue by Brotbeck** [jmmorato/openddsharp#6] opened 2018-09-10 10:27 UTC
I try to launch the subscriber on a host different from the publisher in the intranet but the subscriber never gets any data from the publisher. The Publisher also never sees the subscriber. In the Internet i saw this is a problem of the transport. But i don't know where I set the configuration of the transport. How can I get running the Helloworld Example?

**Comment by jmmorato** [comment] 2018-09-10 16:58
I cannot reproduce it. Tested with different accounts and different Windows version and worked successfully. It should be something else.

**Comment by jmmorato** [comment] 2018-09-11 13:46
Glad that you found the problem. I'll close the issue then.

**Closed by jmmorato** 2018-09-11 13:46 UTC
