### ISSUE TITLE
More #Include Issues? 

### ISSUE THREAD

**Issue by InfoShellTex** [jmmorato/openddsharp#184] opened 2023-06-23 23:19 UTC
Hello, im new to DDS and IDLs. im using this OpenDDSharp to create a .NET application to use the library. The helloWorld  example works but as most cases (i would assume), the idls get more complex than that. I'm trying to get it to work with importing other idl files. this may be a similar issue to #99 . But not the exact same error. I get errors like "error C3646: 'foot': unknown override specifier " I attached a zip of my solution file and the 2 edited idl files. The real idl files im trying to use is some idl files ros2 uses like the vector3 and Accel idl file, they are also attached. Not really sure what the main issue is so im looking for help.
This is also using Visual Studio 2022 and Windows 10 build 19045.3086. I tried building in Visual studio 2019, but same errors.
[testDDS.zip](https://github.com/jmmorato/openddsharp/files/11853719/testDDS.zip)
[Accel.txt](https://github.com/jmmorato/openddsharp/files/11853731/Accel.txt)
[Vector3.txt](https://github.com/jmmorato/openddsharp/files/11853733/Vector3.txt)

**Comment by jmmorato** [comment] 2023-06-24 08:51
Hi, first of all thanks for reproducer.

The code generator is being rewritten for next OpenDDSharp release version so the problem you are facing is gone by the refactoring. Still, when I tried your reproducer with the latest pre-release version, I found another issue with the includes paths (a new PR #185 to fix it).

Once the reproducer is fixed you will face another issue because the ros2 framework you are trying to use. All IDL files used in your final project must be auto-generated by opendddsharp in order to generate the C# code, so somehow we need to compile ros2 framework as well in the same or in a separted OpenDDSharp IDL project.

**Comment by InfoShellTex** [comment] 2023-06-25 15:40
In theory, if i use all of ros2s' IDL files inside this OpenDDSharp library, i should be able to talk using ros2. Meaning, I'm thinking  you could use ros2s' test publisher process/script and use a .NET application to create a subscriber using OpenDDSharp using the same IDLs. And assuming its the right message, domain, topic, etc., they should receive/send like normal. According to ros2, they use fastDDS by default. So im thinking fastDDS should be able to to talk to an OpenDDS implementation.

1. Does that sound possible/feasible? because if im interpreting what your saying, it sounds like its not. OR very difficult. 
2. To fully clarify, Are you saying the .idl files themselves need to be generated from openDDSharp? or are you just talking about the Generated {idlFileName}TypeSupport classes?

Thanks for the initial response

**Comment by jmmorato** [comment] 2023-06-26 14:34
_1. Does that sound possible/feasible? because if im interpreting what your saying, it sounds like its not. OR very difficult._
   It is possible, fastDDS and OpenDDS should be compatible on the wire when the types are well known on each side
_2. To fully clarify, Are you saying the .idl files themselves need to be generated from openDDSharp? or are you just talking about the Generated {idlFileName}TypeSupport classes?_
   The TypeSupport classes need to be generated with OpenDDS (C++ code) and OpenDDSharp (C# code) in order to be used by your subscriber .NET application

**Comment by InfoShellTex** [comment] 2023-06-26 18:39
okay yeah  that's what i was thinking. some ros2 .idl messages couldn't be used to generate the support classes. Those Vector and Accel txt files are 2 of many messages, but i tried these 2 alone and they wouldn't work, one of the issues is that include that's mentioned.

**Comment by jmmorato** [comment] 2023-10-27 16:27
Fix released in latest version 3.250.2

**Closed by jmmorato** 2023-10-27 16:27 UTC
