### ISSUE TITLE
Writing complex struct results in InvalidOperationException

### ISSUE THREAD

**Issue by MarcoRoccagli** [jmmorato/openddsharp#130] opened 2022-10-17 08:00 UTC
Hello, again.
I was testing a complex idl (the one located in openddsharp/Tests/TestStandard/IDL/Test.idl).
I just created a publisher project and a subscriber project and created the corrispettive topics (NestedStruct,TestStruct,Athlete,Result,AthleteResult).
In the subscriber project, when i try to write something in TestStruct (the very complex one), the write just crashes with InvalidOperationException 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'
The other created topics, just write fine.
Any ideas for this?
Thanks for your attention

EDIT:
FYI, just investigating a little bit, when i try to re-create the writer (after the crash) for publisher, in the DCPSInfoRepo console window, it prompts:

(21384|27708) EXCEPTION, (%P|%t) ERROR: Exception caught in DCPS_IR_Publication::add_associated_subscription:
system exception, ID 'IDL:omg.org/CORBA/TRANSIENT:1.0'
OMG minor code (2), described as 'No usable profile in IOR.', completed = NO

Invalid publication detected, NOT notifying subscription of association
(21384|27708) ERROR: DCPS_IR_Domain::remove_dead_participants () Removing dead participant 0xb8f5bb80 id 01030000.30e110f7.00000003.000001c1(c6dd6cd2)
(21384|27708) ERROR: DCPS_IR_Subscription::remove_associated_publication: subscription 01030000.30e110f7.00000004.00000507(62961243) failed to remove publication 01030000.30e110f7.00000003.00000102(c4b0ffd8) at bb4085c0.

**Comment by jmmorato** [comment] 2022-10-18 16:43
Hi,

Almost all unit tests are using `TestStruct` for samples publications, so I would say the error is depending of the values you are sending.

Can you post the exact values you are using or the project reproducer?

Thanks for reporting.

**Comment by Mirarchi** [comment] 2022-10-18 19:11
Hi i forgot to mention that the issue doesn't occur on the project which firstly creates the topic, but occurs when a second program that creates the same exact topic and after successfully creating both a datareader and a datawriter tries to take/write the data from/to other side.
So to recap:
First program connects to repo and creates the topic. Creates a datareader related to a subscriber and a datawriter related to a publisher and takes/writes data without problem.
Second program connects to repo and creates the same exact topic of first program. Also here are created a publisher/subscriber and relative datawriter and datareader. If i try to write or take data i have the issue.

Thanks for your attention

**Comment by jmmorato** [comment] 2022-10-22 09:47
I couldn't reproduce the issue. 

I tried with RTPS and DCPSInfoRepo but in both cases I received the samples without errors. As you explained in your last comment, I created two instances of the software with a datawriter and a datareader and send samples first with one and then with the other.

Take a look to the code I used to check for differences in your app:
[ComplexStructureTest.zip](https://github.com/jmmorato/openddsharp/files/9844012/ComplexStructureTest.zip)

**Comment by MarcoRoccagli** [comment] 2022-10-24 06:22
Thanks for your feedback. I will try to reproduce the issue and let you know the results.

**Comment by jmmorato** [comment] 2022-10-24 06:27
Yesterday I found an error in the templates for the IDL project https://github.com/jmmorato/openddsharp/pull/131

If you generated the IDL project with the dotnet template it should be bugged. As workaround until the fix is released, just replace the `MarshalHelper.cs` in your project with the one found in https://github.com/jmmorato/openddsharp/blob/develop/Sources/OpenDDSharp.Templates/templates/IdlProject/Helpers/MarshalHelper.cs

**Comment by MarcoRoccagli** [comment] 2022-10-24 09:39
Hi, i just found the issue and this not a OpenDDSSharp issue but my fault.
I'm developing a sort of DDSExplorer that finds the topics created in the DCPSInfoRepo.
From here then via the "TopicData" policy, i can access to the IDL data and build at runtime the C++ wrapper and the .NET assembly correcly.
Once that i was able to access via reflection to the properties of the created assembly.
To solve the problem, i needed to add the "Windows" constant in the generated .NET project because this defines the correct marshalling mode some of the IDL defined structures.
With this i'm able to write and read the entity correctly.
Anyway now when i try to parse the "WCharArrayField" property via reflection it returns a ushort array instead of char array as defined in the IDL, but for this i think that i will open a dedicated issue.
Thanks anyway for your support.
Regards

**Comment by jmmorato** [comment] 2022-10-24 16:04
Great that you found it!!

Let's close this issue and feel free to open a new one when you have the full info about the `WCharArrayField `

**Closed by jmmorato** 2022-10-24 16:04 UTC
